default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_meshi_dev

test:
  <<: *default
  database: pai_meshi_test

production:
  <<: *default
  database: <%= ENV['PAI_MESHI_DATABASE'] %>
  host: <%= ENV['PAI_MESHI_HOST'] %>
  username: <%= ENV['PAI_MESHI_USERNAME'] %>
  password: <%= ENV['PAI_MESHI_PASSWORD'] %>
